export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_COMPANY = "SET_CURRENT_COMPANY";
export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const GET_COMPANY = "GET_COMPANY";
